services:
  - type: web
    name: makamandag-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: makamandag-db
          property: connectionString

databases:
  - name: makamandag-db
    plan: free